- name: Upload blockpage
  set_fact:
    script: |
      {{ script }}
      CONFIG UPLOAD httpproxy_blockpage{{ blockpage.index }} < {{ blockpage.file }}
  when:
     - "blockpage.file is defined"
     - "firmware_version.value is version('4.8.1', '<')"

- name: Upload blockpage
  set_fact:
    script: |
      {{ script }}
      CONFIG FILE UPLOAD file=httpproxy_blockpage{{ blockpage.index }} < {{ blockpage.file }}
  when:
    - "blockpage.file is defined"
    - "firmware_version.value is version('4.8.1', '>=')"

- name: Rename blockpage
  set_fact:
    script: |
      {{ script }}
      CONFIG URLFILTERING BLOCKPAGE UPDATE index={{ blockpage.index }} name="{{ blockpage.name }}"
  when: "blockpage.name is defined"
