argument_specs:
  main:
    short_description: Configuration backup
    description:
      - This role backups and restores Stormshield Network Security appliance configurations.
    options:
      backup_path:
        description: Local path where backup files are stored.
        type: "str"
        required: true
      backup:
        description: File name of the backup
        type: "str"
      restore:
        description: File name of the backup file to restore
        type: "str"
      password:
        description: Optionnal password of the backup file
        type: "str"
      timestamp_prefix:
        description: Prefix the filename with the current timestamp
        type: "bool"
        default: false
      list:
        description: List of configuration to restore.
        type: "list"
        elements: "str"
        default: all