argument_specs:
  main:
    short_description: Firmware update
    description:
      - This role update the firmware of Stormshield Network Security appliances.
    options:
      download_path:
        description: Folder where the downloaded firmware files ares stored
        type: "str"
        default: "~/Downloads"
      version:
        description: Firmware version to install
        type: "str"
        required: true
      arch:
        description: Appliance architecture
        type: "str"
        default: "inventory `arch` variable"
      model:
        description: Appliance model
        type: "str"
        default: "inventory `model` variable"
      system_clone:
        description: Backup the system partition before update
        type: "bool"
        default: false