- name: Copy current version to backup partition
  sns_command:
    appliance: "{{ appliance }}"
    script: |
      SYSTEM CLONE type=dump
    force_modify: "{{ hostvars[inventory_hostname].force_modify | default(false) }}"
  when: system_clone == True

- name: Update SNS appliance
  sns_command:
    appliance: "{{ appliance }}"
    script: |
      SYSTEM UPDATE UPLOAD < {{ download_path }}/fwupd-{{ version }}-SNS-{{ arch }}-{{ model }}.maj
      SYSTEM UPDATE ACTIVATE
    expect_disconnect: True
    force_modify: "{{ hostvars[inventory_hostname].force_modify | default(false) }}"

- pause:
    minutes: 1

- name: Wait for firewall update
  sns_command:
    appliance: "{{ appliance }}"
    command: SYSTEM PROPERTY
  ignore_errors: yes
  register: result
  until: "'ret' in result and result.ret == 100"
  retries: 20
  delay: 30
  changed_when: False
