argument_specs:
  main:
    short_description: DNS configuration
    description:
      - This role configures DNS servers on Stormshield Network Security appliances.
    options:
      dns_servers:
        description: List of DNS servers with their object/host names and their IP addresses.
        type: "list"
        elements: "str"
        required: true
        options:
          host:
            type: "str"
            description: Object name
            required: true
          ip:
            type: "str"
            description: DNS server IP address
            required: true
