argument_specs:
  main:
    short_description: URL configuration
    description:
      - This role configures URL/CN filtering on Stormshield Network Security appliances.
    options:
      base:
        type: "str"
        choices: [cloud, embedded]
        description: Choose between cloud or embedded database.
      urlgroups:
        type: "list"
        elements: "dict"
        description: "List of url groups"
        options:
          name:
            type: str
            description: url group name
          comment:
            type: "str"
            description: Object comment
          urls:
            type: "list"
            elements: "dict"
            description: List of urls
            options:
              url:
                type: "str"
                description: url
              comment:
                type: "str"
                description: Comment
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      cngroups:
        type: "list"
        elements: "dict"
        description: List of CN groups
        options:
          name:
            type: "str"
            description: url group name
          comment:
            type: "str"
            description: Comment
          cns:
            type: "list"
            elements: "dict"
            description: "List of CN"
            options:
              cn:
                type: "str"
                description: Common name
              comment:
                type: "str"
                description: Comment
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      urlcategorygroups:
        type: "list"
        elements: "dict"
        description: List of url category groups
        options:
          name:
            type: "str"
            description: Category group
          comment:
            type: "str"
            description: Comment
          members:
            type: "list"
            elements: "str"
            description: List of url groups
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      cncategorygroups:
        type: "list"
        elements: "dict"
        description: List of cn category groups
        options:
          name:
            type: "str"
            description: Category group
          comment:
            type: "str"
            description: Comment
          members:
            type: "list"
            elements: "str"
            description: List of CN groups
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      state:
        type: "str"
        description: "If set to `absent`, deletes the objects."
      urlfiltering:
        type: "list"
        elements: dict
        description: Define the URL filtering slots and rules.
        options:
          index:
            type: int
            description: Slot number
            required: true
          name:
            type: str
            description: Slot name
          comment:
            type: str
            description: Slot comment
          rules:
            type: list
            elements: dict
            description: URL filtering rules
            options:
              ruleid:
                type: int
                description: Rule id
              state:
                type: "str"
                description: Rule state
                choices: ["on", "off"]
              action:
                type: "str"
                choices: [pass, block, blockpage0, blockpage1, blockpage2, blockpage3]
                description: Rule action
              urlgroup:
                type: str
                description: "<urlgroup object|urlcategory group object>"
              comment:
                type: str
                description: Rule comment
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      sslfiltering:
        type: list
        elements: dict
        description: Define the SSL filtering slots and rules
        options:
          index:
            type: int
            description: Slot number
            required: true
          name:
            type: str
            description: Slot name
          comment:
            type: str
            description: Slot comment
          rules:
            type: list
            elements: dict
            description: SSL filtering rules
            options:
              ruleid:
                type: int
                description: Rule id
              state:
                type: "str"
                description: Rule state
                choices: ["on", "off"]
              action:
                type: "str"
                choices: [decrypt, nodecrypt, block, blockpage0, blockpage1, blockpage2, blockpage3]
                description: Rule action
              cngroup:
                type: str
                description: "<cngroup object|cncategory group object>"
              comment:
                type: str
                description: Rule comment
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      blockpages:
        type: list
        elements: dict
        description: Upload the HTML files for block pages.
        options:
          index:
            type: int
            description: Index 0 to 4
          file:
            type: str
            description: File path of the template to upload
          name:
            type: "str"
            description: Page name
