argument_specs:
  main:
    short_description: Object configuration
    description:
      - This role updates the object base of Stormshield Network Security appliances.
    options:
      state:
        description: "If set to `absent`, delete the objects. The Internet object can't be deleted and is common to local and global base."
      scope:
        type: "str"
        choices: [global, local]
        default: local
        description: "Use global or local object base"
      csvfileimport:
        type: "str"
        description: CSV file to import, see https://documentation.stormshield.eu/SNS/v4/en/Content/User_Configuration_Manual_SNS_v4/Appendix_B_-_Objects_base_structure/Appendix_B_-_Objects_base_structure.htm for the file format.
      hosts:
        type: "list"
        elements: "dict"
        description: List of host objects
        options:
          name:
            type: "str"
            description: Host name
          ip:
            type: "str"
            description: ip address
          ipv6:
            type: "str"
            description: ipv6 address
          type:
            type: "str"
            choices: [router, server, host]
            description: Object type
          resolve:
            type: "str"
            choices: [static, dynamic, manual]
            description: DNS resolution
          mac:
            type: "str"
            description: Mac address
          color:
            type: "str"
            description: Object color
          comment:
            type: "str"
            description: Object comment
      ranges:
        type: "list"
        elements: "dict"
        description: List of range objects
        options:
          name:
            type: "str"
            description: Range name
          begin:
            type: "str"
            description: First IP of the range
          end:
            type: "str"
            description: Last IP of the range
          beginv6:
            type: "str"
            description: First IPv6 of the range
          endv6:
            type: "str"
            description: Last IPv6 of the range
          color:
            type: "str"
            description: Object color
          comment:
            type: "str"
            description: Object comment
      networks:
        type: "list"
        elements: "dict"
        description: List of network objects
        options:
          name:
            type: "str"
            description: Network name
          ip:
            type: "str"
            description: Network IPV4 address
          mask:
            type: "str"
            description: Network mask
          ipv6:
            type: "str"
            description: Network IPv6 address
          prefixlenv6:
            type: "str"
            description: IPv6 prefix length
          color:
            type: "str"
            description: Object color
          comment:
            type: "str"
            description: Object comment
      netgroups:
        type: "list"
        elements: "dict"
        description: List of network group objects
        options:
          name:
            type: "str"
            description: Group name
          comment:
            type: "str"
            description: Object comment
          members:
            type: "list"
            elements: "str"
            description: Members of the group
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      services:
        type: "list"
        elements: "dict"
        description: List of service objects
        options:
          name:
            type: "str"
            description: Service name
          port:
            type: "int"
            description: Port number
          proto:
            type: "str"
            choices: [tcp, udp, any]
            description: Protocol
          toport:
            type: int
            description: High port number
          color:
            type: "str"
            description: Object color
          comment:
            type: "str"
            description: Object comment
      servicegroups:
        type: "list"
        elements: "dict"
        description: List of service group objects
        options:
          name:
            type: "str"
            description: Service group name
          comment:
            type: "str"
            description: Object comment
          members:
            type: "list"
            elements: "str"
            description: Members of the group
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      protocols:
        type: "list"
        elements: "dict"
        description: List of protocol objects
        options:
          name:
            type: "str"
            description: Protocol name
          protonumber:
            type: "int"
            description: IP protocol number
          color:
            type: "str"
            description: Object color
          comment:
            type: "str"
            description: Object comment
      timeobjects:
        type: "list"
        elements: "dict"
        description: List of time objects
        options:
          name:
            type: "str"
            description: Time object name
          time:
            type: "str"
            description: (|hh:mm-hh:mm[;hh:mm-hh:mm]...)
          weekday:
            type: "str"
            description: (|dow[-dow][;dow[-dow]]...)
          yearday:
            type: "str"
            description: (|mm:dd[-mm:dd][;mm:dd[-mm:dd]]...)
          date:
            type: "str"
            description: (|yyyy:mm:dd[:hh:mm][-yyyy:mm:dd[:hh:mm]])
          color:
            type: "str"
            description: Object color
          comment:
            type: "str"
            description: Object comment
      fqdnobjects:
        type: "list"
        elements: "dict"
        description: List of FQDN objects
        options:
          name:
            type: "str"
            description: fqdn
          ip:
            type: "str"
            description: IP address
          ipv6:
            type: "str"
            description: IPv6 address
          color:
            type: "str"
            description: Object color
          comment:
            type: "str"
            description: Object comment
      geogroups:
        type: "list"
        elements: "dict"
        description: List of geo group objects
        options:
          name:
            type: "str"
            description: Geo group name
          comment:
            type: "str"
            description: Object comment
          members:
            type: "list"
            elements: "str"
            description: Members of the group
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      iprepgroups:
        type: "list"
        elements: "dict"
        description: List of IP reputation objects
        options:
          name:
            type: "str"
            description: IP reputation group name
          comment:
            type: "str"
            description: Object comment
          members:
            type: "list"
            elements: "str"
            description: Members of the group
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      routers:
        type: "list"
        elements: "dict"
        description: List of router objects
        options:
          name:
            type: "str"
            description: Router name
          monitor:
            type: "str"
            choices: [ICMP, TCP_PROBE]
            description: Monitoring type
          comment:
            type: "str"
            description: Object comment
          tries:
            type: "int"
            description: Number of tries
          wait:
            type: "int"
            description: Wait time in seconds
          frequency:
            type: "int"
            description: Frequency in seconds
          gatewaythreshold:
            type: "int"
            description: Gateway number threshold
          activateallbackup:
            type: "str"
            choices: [on, off]
            description: Activate all backups flag
          loadbalancing:
            type: "str"
            choices: [none, connhash, srchash]
            description: Load balancing type
          onfailpolicy:
            type: "str"
            choices: [pass, block]
          gateways:
            type: "list"
            elements: "dict"
            options:
              type:
                type: "str"
                choices: [principalgateway, backupgateway]
                description: Type of gateway
              host:
                type: "str"
                description: Host object name,
              check:
                type: "str"
                description: Object (host|hostgroup)
              weight:
                type: "int"
                description: Gateway weight
              monitor:
                type: "str"
                choices: [none, icmp, all]
                description: Monitoring type
          mode:
            type: "str"
            choices: [add, reset, del]
            default: reset
            description: Object add mode
      internet:
        type: "dict"
        description: Configuration of the Internet object
        options:
          object:
            type: "str"
            description: Object (host, network, range, group)
          operator:
            type: "str"
            choices: [ne, eq]
            description: Operator
      qos:
        type: "dict"
        description: QoS configuration
        options:
          bandwidth:
            type: "int"
            description: Bandwidth in kbps
          drop:
            type: "int"
            choices: [0, 1]
            description: Drop algorithm 0 (TailDrop) 1 (Blue)
          defaultqueue:
            type: "str"
            description: Qid name or bypass
          qids:
            type: "list"
            elements: "dict"
            description: List of QOS objects
            options:
              name:
                type: "str"
                description: Object name
              comment:
                type: "str"
                description: Object comment
              type:
                type: "str"
                choices: [CBQ, PRIQ]
                description: Type of QID
              min:
                type: "int"
                description: Minimum bandwidth (CBQ)
              min_rev:
                type: "int"
                description: Minimum reverse bandwidth (CBQ)
              max:
                type: "int"
                description: Maximum bandwidth (CBQ)
              max_rev:
                type: "int"
                description: Maximum reverse bandwidth (CBQ)
              pri:
                type: "int"
                description: Priority (PRIQ)
              color:
                type: "str"
                description: Object color
              length:
                type: "int"
                description: Queue length
              lengthrev:
                type: "int"
                description: Reverse queue length
              prioritizeack:
                type: "str"
                choices: ["on", "off"]
                description: ACK prioritization
              prioritizelowdelay:
                type: "str"
                choices: ["on", "off"]
                description: Prioritize low delay
          tbrs:
            type: "list"
            elements: "dict"
            description: List of token bucket regulator objects
            options:
              name:
                type: "str"
                description: tbr name
              bandwidth:
                type: "int"
                description: Bandwidth
              bandwidthin:
                type: "int"
                description: IN bandwidth
          interfaces:
            type: "list"
            elements: "dict"
            description: Interface QoS configuration
            options:
              name:
                type: "str"
                description: Interface name
              tbr:
                type: "str"
                description: TBR name
              defaultqueue:
                type: "str"
                description: "Default queue: qid name or bypass"
              defaultackqueue:
                type: "str"
                description: "Default ack queue: qid name or bypass"
