argument_specs:
  main:
    short_description: Policy configuration
    description:
      - This role configures filter and NAT policies of Stormshield Network Security appliances.
    options:
      slotname:
        type: "str"
        description: "Name of the slot"
      comment:
        type: "str"
        description: "Slot comment"
      scope:
        type: "str"
        choices: [local, global]
        default: local
        description: "Use local or global slot"
      slot:
        type: "int"
        description: "Slot number"
        required: true
      activate:
        type: bool
        choices: [yes, no]
        description: "Activate the slot"
        default: yes
      mode:
        type: "str"
        choices: [add, reset, del]
        default: reset
        description: Rule add mode
      filter:
        type: "list"
        elements: "dict"
        description: "Filter rules"
        options: &rules_def
          position:
            type: "int"
            description: Insert at line N
          name:
            type: "str"
            description: "Rule name"
          state:
            type: "str"
            choices: ["on", "off"]
            description: Rule state
          action:
            type: "str"
            choices: [pass, block, deleg, reset, log, decrypt, nat]
            description: Rule action
          loglevel:
            type: "str"
            choices: [none, log, minor, major]
            description: Rule log level
          noconnlog:
            type: "str"
            description: "Don't log the connection all|([disk],[syslog],[ipfix])"
          count:
            type: "str"
            choices: ["on", "off"]
          rate:
            type: "str"
            description: "(\"\"|<tcp>,<udp>,<icmp>,<request>)"
          synproxy:
            type: "str"
            choices: ["on", "off"]
            description: "SYN proxy"
          settos:
            type: "str"
            description: "Set TOS Field (\"\"|1-254)"
          qosid:
            type: "str"
            description: "QID name"
          ackqosid:
            type: "str"
            description: "ACK QID name"
          qosfairness:
            type: "str"
            choices: [state, user, host]
            description: "QoS fairness"
          route:
            type: "str"
            description: "Use route (\"\"|<objrouter>|<hostname>|<ipaddr>)"
          inspection:
            type: "str"
            choices: [firewall, ids, ips]
            description: "Inspection level"
          antivirus:
            type: "str"
            choices: ["on", "off"]
            description: "Use Antivirus analysis"
          sandboxing:
            type: "str"
            choices: ["on", "off"]
            description: "Use sandboxing analysis"
          antispam:
            type: "str"
            choices: ["on", "off"]
            description: "Use antispam analysis"
          proxycache:
            type: "str"
            choices: ["on", "off"]
            description: "Use cache proxy"
          ftpfiltering:
            type: "str"
            choices: ["on", "off"]
            description: "Use FTP filtering"
          urlfiltering:
            type: "str"
            description: "URL policy index (\"\"|<0-9>)"
          mailfiltering:
            type: "str"
            description: "Mail policy index (\"\"|<0-9>)"
          sslfiltering:
            type: "str"
            description: "SSL policy index (|<0-9>)"
          fwservice:
            type: "str"
            choices: ["", httpproxy, webportal]
            description: "Service"
          webportalexcept:
            type: "str"
            description: "Web portal exception (\"\"|urlgroup[,urlgroup[,urlgroup[,...]]])"
          inbound:
            type: "str"
            choices: ["", sip_udp]
            description: "Inbound"
          schedule:
            type: "str"
            description: "Rule scheduling (anytime|<time object>)"
          securityinspection:
            type: "str"
            description: "Security inspection index (\"\"|<0-9>)"
          tos:
            type: "str"
            description: "Filter TOS field (\"\"|<1-254>)"
          ipstate:
            type: "str"
            choices: ["on", "off"]
            description: "IP state"
          ipproto:
            type: "str"
            description: " IP protocol(any|<IP protocol name>)"
          icmptype:
            type: "str"
            description: "ICMP type (\"\"|<0-255>)"
          icmpcode:
            type: str
            description: "ICMP code (\"\"|<0-255>)"
          proto:
            type: "str"
            description: "Application protocol (auto|none|<app protocol name>)"
          srcuser:
            type: "str"
            description: "Source user (\"\"|any|unknown|[!]<user>|[!]<usergroup>)"
          srcusertype:
            type: "str"
            description: "Source user type (\"\"|user|group)"
          srcuserdomain:
            type: "str"
            description: "Source user domain (\"\"|<domain name>)"
          srcusermethod:
            type: "str"
            choices: ["", plain, spnego, ssl, radius, kerberos, agent-ad, openvpn, ipsec, guest, agent-guard]
            description: "Source user authentication method"
          srctarget:
            type: "str"
            description: "Source target (any|[!]<objectname>[,<objectname>[,<objectname>[,...]]])"
          srcportop:
            type: "str"
            choices: [eq, ne, gt, lt]
            description: "Source port operator"
          srcport:
            type: "str"
            description: "Source port (any|<objectservice>[,<objectservice>[,<objectservice>[,...]]])"
          srcif:
            type: "str"
            description: "Source interface (any|<interface name>)"
          srcgeo:
            type: "str"
            description: "Source geo object (<objectgeo[|<objectgeo>[|...]]])"
          srciprep:
            type: "str"
            description: =(<objectiprep[|<objectiprep>[|...]]])]
          srchostrep:
            type: "int"
            description: "Source host reputation filter (<0-65535>)"
          srchostrepop:
            type: "str"
            choices: [lt, gt]
            description: "Source host reputation operator"
          via:
            type: "str"
            choices: [any, sslvpn, httpproxy, ipsec, sslproxy, none]
            description: "Via"
          dsttarget:
            type: "str"
            description: "Destination target (any|[!]<objectname>[,<objectname>[,<objectname>[,...]]])"
          dstportop:
            type: "str"
            choices: [eq, ne, gt, lt]
            description: "Destination port operator"
          dstport:
            type: "str"
            description: "Destination port (any|<objectservice>[,<objectservice>[,<objectservice>[,...]]])"
          dstif:
            type: "str"
            description: "Destination interface (any|<interface name>)"
          dstgeo:
            type: "str"
            description: "Destination geo object(<objectgeo[|objectgeo[|...]]])"
          dstiprep:
            type: "str"
            description: "Destination IP reputation (<objectiprep[|objectiprep[|...]]])]"
          dsthostrep:
            type: int
            description: "Destination host reputation (<0-65535>)"
          dsthostrepop:
            type: "str"
            choices: [lt, gt]
            description: "Destination host reputation operator"
          natsrctarget:
            type: "str"
            description: "NAT source target (\"\"|original|<object name>)"
          natsrclb:
            type: "str"
            choices: ["none", roundrobin, srchash, connhash, random]
            description: "NAT source load balancing algorithm"
          natsrcarp:
            type: "str"
            choices: ["on", "off"]
            description: "NAT source ARP"
          natsrcportop:
            type: "str"
            choices: [eq, ne, gt, lt]
            description: "NAT source port operator"
          natsrcport:
            type: "str"
            description: "NAT source port (original|<objectservice>|<port range>)"
          natsrcportlb:
            type: "str"
            choices: ["none", "random"]
            description: "NAT source port loadbalancing algorithm"
          natdsttarget:
            type: "str"
            description: "NAT destination target (\"\"|original|<object name>)"
          natdstlb:
            type: "str"
            choices: ["none", roundrobin, srchash, connhash, random]
            description: "Load balancing algorithm on NAT destination IP"
          natdstarp:
            type: "str"
            choices: ["on", "off"]
            description: "NAT destination ARP"
          natdstportop:
            type: "str"
            choices: [eq, ne, gt, lt]
            description: "NAT destination port operator"
          natdstport:
            type: "str"
            description: "NAT destination port (original|<objectservice>|<port range>)"
          natdstportlb:
            type: "str"
            choices: ["none", roundrobin, srchash, connhash, random]
            description: "Load balancing algorithm on nat destination port"
          beforevpn:
            type: "str"
            choices: ["on", "off"]
            description: "Apply before VPN"
          enforceipsecforward:
            type: "str"
            choices: ["on", "off"]
            description: "Enforce IPsec forward"
          enforceipsecreverse:
            type: "str"
            choices: ["on", "off"]
            description: "Enforce IPsec reverse routing"
          comment:
            type: "str"
            description: "Rule comment"
          rulename:
            type: "str"
            description: "Rule name"
      nat:
        type: "list"
        elements: "dict"
        description: "NAT rules"
        options: *rules_def
