- hosts: all
  tasks:
  - name: Get appliance information
    stormshield.sns.sns_command:
      appliance: "{{ hostvars[inventory_hostname].appliance }}"
      command: SYSTEM PROPERTY
    register: sysprop

  - name: Extract version
    stormshield.sns.sns_getconf:
      result: "{{ sysprop.result }}"
      section: Result
      token: Version
    register: version

  - name: Extract model
    stormshield.sns.sns_getconf:
      result: "{{ sysprop.result }}"
      section: Result
      token: Model
    register: model

  - name: Get appliance name
    stormshield.sns.sns_command:
      appliance: "{{ hostvars[inventory_hostname].appliance }}"
      command: SYSTEM IDENT
    register: ident

  - name: Extract system name
    stormshield.sns.sns_getconf:
      result: "{{ ident.result }}"
      section: Result
      token: SystemName
    register: sysname

  - debug:
      msg: "Appliance: {{ inventory_hostname }}, system name: {{ sysname.value }}, model: {{ model.value }}, firmware version: {{ version.value }}"
